### ISSUE TITLE
no output back

### ISSUE THREAD

**Issue by iNoSec** [snovvcrash/FwdSh3ll#2]
Hi,
First i would like to thank you for working on this code, that's very useful!!!
That's being said, i come to my "problem" i try this on the pentesterlab.com shellshock iso locally and impossible to have the output of the command back, and i cant figure why, maybe i must tweak the payload but if you can look at it.
The exercise link: https://pentesterlab.com/exercises/cve-2014-6271
The first time i did i made a bash script to automate the work and it work perfectly https://github.com/iNoSec/Webshell-by-Me/blob/master/shellshock.sh

Hope you can look at it, anyway thanks

**Comment by snovvcrash** [comment]
Hello there,

Thanks for the kind words, I really appreciate it!

As for your question: there was no output of the executed command in the exercise you are talking about because the [PentesterLab's task](https://pentesterlab.com/exercises/cve-2014-6271/course) requires running commands as `/bin/bash -c '<CMD>'` to successfully exploit ShellShock. Previous version of FwdSh3ll was doing just `<CMD>` when running the command, so it actually would have worked if you had had specified the `/bin/bash -c` prefix (see the screenshot below).

I have updated the framework and now it always runs commands starting with this expression. Also there are quite a few improvements including Metasploit-like usage experience, give it a glance!

![pentesterlab.png](https://user-images.githubusercontent.com/23141800/61952433-8618de80-afbc-11e9-8ef3-4f43562bf435.png)
